name: Create index.html from readme.md

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make convert.sh executable
        run: chmod +x ./convert.sh

      - name: Run convert.sh with Pandoc in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            pandoc/core:3.5 \
            bash convert.sh
