name: Create index.html from readme.md

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Make convert.sh executable
        run: chmod +x convert.sh

      - name: Run convert.sh
        run: ./convert.sh

      - uses: docker://pandoc/core:3.5
