name: Create index.html from readme.md

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Make convert.sh executable
        run: chmod +x ./convert.sh

      - name: Run convert.sh
        run: ./convert.sh
